config/routes.rb
Rails.application.routes.draw do
  resources :time_off_instances
  resources :employees, :path => '/'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :time_off_instances
end

app/models/time_off_instance.rb
class TimeOffInstance < ActiveRecord::Base
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    TimeOffInstance.all.map { |e|
      if e.employee_id == @employee.id
        e.destroy
      end
    }
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :hours_left)
    end

    def get_name
      return name
    end
end

app/controllers/time_off_instances_controller.rb
class TimeOffInstancesController < ApplicationController
  before_action :set_time_off_instance, only: [:show, :edit, :update, :destroy]

  # GET /time_off_instances
  # GET /time_off_instances.json
  def index
    @time_off_instances = TimeOffInstance.all
  end

  # GET /time_off_instances/1
  # GET /time_off_instances/1.json
  def show
  end

  # GET /time_off_instances/new
  def new
    @time_off_instance = TimeOffInstance.new
    @employees = Employee.all
  end

  # GET /time_off_instances/1/edit
  def edit
    @employees = Employee.all
  end

  # POST /time_off_instances
  # POST /time_off_instances.json
  def create
    @time_off_instance = TimeOffInstance.new(time_off_instance_params)
    #@time_off_instance.employee.hours_left -= @time_off_instance.hours_used
    respond_to do |format|
      if @time_off_instance.save
        self.use_pto_hours
        #print "HERE HERE  HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE HERE"
        format.html { redirect_to @time_off_instance, notice: 'Time off instance was successfully created.' }
        format.json { render :show, status: :created, location: @time_off_instance }
      else
        format.html { render :new }
        format.json { render json: @time_off_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_off_instances/1
  # PATCH/PUT /time_off_instances/1.json
  def update
    respond_to do |format|
      self.unuse_pto_hours
      if @time_off_instance.update(time_off_instance_params)
        self.use_pto_hours
        format.html { redirect_to @time_off_instance, notice: 'Time off instance was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_off_instance }
      else
        format.html { render :edit }
        format.json { render json: @time_off_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_off_instances/1
  # DELETE /time_off_instances/1.json
  def destroy
    self.unuse_pto_hours
    @time_off_instance.destroy
    respond_to do |format|
      format.html { redirect_to time_off_instances_url, notice: 'Time off instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unuse_pto_hours
    @time_off_instance.employee.hours_left += @time_off_instance.hours_used
    @time_off_instance.employee.save
  end

  def use_pto_hours
    @time_off_instance.employee.hours_left -= @time_off_instance.hours_used
    @time_off_instance.employee.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_off_instance
      @time_off_instance = TimeOffInstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_off_instance_params
      params.require(:time_off_instance).permit(:employee_id, :hours_used, :reason)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/time_off_instances_helper.rb
module TimeOffInstancesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hours_left %><br>
    <%= f.text_field :hours_left %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>
<% if !@employees.empty? %>
  <table border=2>
    <thead>
      <tr>
        <th>Name</th>
        <th>Hours left</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.hours_left %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p>There are currently no employees in the database</p>
<% end %>
<br>

<%= link_to 'New Employee', new_employee_path %>

<br>
<h1>Time Off</h1>
<%= link_to 'View Time Off Requests', time_off_instances_path %>
<br>
<%= link_to 'New Time Off Request',  new_time_off_instance_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Hours left:</strong>
  <%= @employee.hours_left %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PtoTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= button_to 'Home', employees_path, :method => "get" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/time_off_instances/_form.html.erb
<%= form_for(@time_off_instance) do |f| %>
  <% if @time_off_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_off_instance.errors.count, "error") %> prohibited this time_off_instance from being saved:</h2>

      <ul>
      <% @time_off_instance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.select :employee_id, @employees.map {|e| [e.name, e.id]} %>
  </div>
  <div class="field">
    <%= f.label :hours_used %><br>
    <%= f.text_field :hours_used %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_off_instances/edit.html.erb
<h1>Editing Time Off Instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_off_instance %> |
<%= link_to 'Back', time_off_instances_path %>

app/views/time_off_instances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Time Off Instances</h1>
<% if !@time_off_instances.empty? %>
  <table border=2>
    <thead>
      <tr>
        <th>Employee</th>
        <th>Hours used</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @time_off_instances.each do |time_off_instance| %>
        <tr>
          <td><%= time_off_instance.employee.name %></td>
          <td><%= time_off_instance.hours_used %></td>
          <td><%= link_to 'Details', time_off_instance %></td>
          <td><%= link_to 'Edit', edit_time_off_instance_path(time_off_instance) %></td>
          <td><%= link_to 'Delete', time_off_instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<p> There are no time off instances in the database</p>
<% end %>
<br>

<%= link_to 'New Time off instance', new_time_off_instance_path %>

app/views/time_off_instances/new.html.erb
<h1>New Time Off Instance</h1>

<%= render 'form' %>

<%= link_to 'Back', time_off_instances_path %>

app/views/time_off_instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @time_off_instance.employee.name %>
</p>

<p>
  <strong>Hours used:</strong>
  <%= @time_off_instance.hours_used %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @time_off_instance.reason %>
</p>

<%= link_to 'Edit', edit_time_off_instance_path(@time_off_instance) %> |
<%= link_to 'Back', time_off_instances_path %>